apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-lightblue-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      name: pod-postgres
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: "moberlin8/postgres-catalog:1.0"
          imagePullPolicy: Always
          env:
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "postgres"
          - name: POSTGRES_DB
            value: "default"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-lightblue-service
  labels:
    app: postgres
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
   - protocol: TCP
     port: 5423
     nodePort: 30006
