apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test-build
spec:
  params:
    - name: repo-url
      default: https://github.com/ibm-cloud-architecture/cloudnative_sample_app
    - name: revision
      default: master
    - name: image-server
      default: image-registry.openshift-image-registry.svc:5000
    - name: image-namespace
      default: tekton-demo
    - name: image-repository
      default: cloudnative_sample_app
  tasks:
    - name: test
      taskRef:
        name: java-test
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)
    - name: build
      runAfter: [test]
      taskRef:
        name: buildah
      params:
        - name: image
          value: $(params.image-server)/$(params.image-namespace)/$(params.image-repository)
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)
