# This workflow deploys the https://cloudnative101.dev/ site.

name: Site Test Build & Deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Setup Node.js 
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install Dependencies
      run: npm install
    - name: Update Submodules
      run: git submodule update --remote --merge --recursive
    - name: Build Test
      run: npm run build --if-present
    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: public
        fqdn: cloudnative101.dev
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
