# This workflow deploys the https://cloudnative101.dev/ site.

name: TestBuild
on:
  pull_request:
    branches: [ master ]

jobs:
  BuildTest:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Setup Node.js 
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install Dependencies
      run: npm install
    - name: Update Submodules
      run: git submodule update --remote --merge --recursive
    - name: Build Test
      run: npm run build --if-present

